//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLauncher.App.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Thai_Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Thai_Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLauncher.App.Languages.Thai_Texts", typeof(Thai_Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบรายการแคช.
        /// </summary>
        internal static string APIChecker_CacheEntryNotFound {
            get {
                return ResourceManager.GetString("APIChecker_CacheEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เชื่อมต่อล้มเหลว.
        /// </summary>
        internal static string APIChecker_ConnectFailure {
            get {
                return ResourceManager.GetString("APIChecker_ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การเชื่อมต่อปิดแล้ว.
        /// </summary>
        internal static string APIChecker_ConnectionClosed {
            get {
                return ResourceManager.GetString("APIChecker_ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมดเวลาการเชื่อมต่อ.
        /// </summary>
        internal static string APIChecker_ConnectionTimeOut {
            get {
                return ResourceManager.GetString("APIChecker_ConnectionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมดเวลาสื่อการกับ Getway.
        /// </summary>
        internal static string APIChecker_GetWayTimeOut {
            get {
                return ResourceManager.GetString("APIChecker_GetWayTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL ไม่ถูกต้อง.
        /// </summary>
        internal static string APIChecker_InvaildSSL {
            get {
                return ResourceManager.GetString("APIChecker_InvaildSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดปัญหาในการเชื่อมต่อ.
        /// </summary>
        internal static string APIChecker_KeepAliveFailure {
            get {
                return ResourceManager.GetString("APIChecker_KeepAliveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อความมีความยาวมากกว่าที่จำกัดไว้.
        /// </summary>
        internal static string APIChecker_MessageLengthLimitExceeded {
            get {
                return ResourceManager.GetString("APIChecker_MessageLengthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดของชื่อมีความผิดพลาด.
        /// </summary>
        internal static string APIChecker_NameResolutionFailure {
            get {
                return ResourceManager.GetString("APIChecker_NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบสิ่งใด.
        /// </summary>
        internal static string APIChecker_NotFound {
            get {
                return ResourceManager.GetString("APIChecker_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL ไม่ถูกกำหนดไว้.
        /// </summary>
        internal static string APIChecker_Null {
            get {
                return ResourceManager.GetString("APIChecker_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออฟไลน์.
        /// </summary>
        internal static string APIChecker_Offline {
            get {
                return ResourceManager.GetString("APIChecker_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออนไลน์.
        /// </summary>
        internal static string APIChecker_Online {
            get {
                return ResourceManager.GetString("APIChecker_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่มาไม่สามารถเข้าถึงได้.
        /// </summary>
        internal static string APIChecker_OriginUnreachable {
            get {
                return ResourceManager.GetString("APIChecker_OriginUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอดำเนินการ.
        /// </summary>
        internal static string APIChecker_Pending {
            get {
                return ResourceManager.GetString("APIChecker_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline ล้มเหลว.
        /// </summary>
        internal static string APIChecker_PipelineFailure {
            get {
                return ResourceManager.GetString("APIChecker_PipelineFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การแก้ปัญหาชื่อพร็อกซีล้มเหลว.
        /// </summary>
        internal static string APIChecker_ProxyNameResolutionFailure {
            get {
                return ResourceManager.GetString("APIChecker_ProxyNameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจพบปัญหาทางฝั่งเซิฟเวอร์.
        /// </summary>
        internal static string APIChecker_ReceiveFailure {
            get {
                return ResourceManager.GetString("APIChecker_ReceiveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำขอถูกยกเลิก.
        /// </summary>
        internal static string APIChecker_RequestCanceled {
            get {
                return ResourceManager.GetString("APIChecker_RequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำขอถูกห้ามโดยนโยบายแคช.
        /// </summary>
        internal static string APIChecker_RequestProhibitedByCachePolicy {
            get {
                return ResourceManager.GetString("APIChecker_RequestProhibitedByCachePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความล้มเหลวของช่องทางที่ปลอดภัย.
        /// </summary>
        internal static string APIChecker_SecureChannelFailure {
            get {
                return ResourceManager.GetString("APIChecker_SecureChannelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งข้อมูลล้มเหลว.
        /// </summary>
        internal static string APIChecker_SendFailure {
            get {
                return ResourceManager.GetString("APIChecker_SendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เซิร์ฟเวอร์ผิดพลาด.
        /// </summary>
        internal static string APIChecker_ServerError {
            get {
                return ResourceManager.GetString("APIChecker_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เซิร์ฟเวอร์มีอาการโอเวอร์โหลด.
        /// </summary>
        internal static string APIChecker_ServerOverloaded {
            get {
                return ResourceManager.GetString("APIChecker_ServerOverloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การละเมิดโปรโตคอลเซิร์ฟเวอร์.
        /// </summary>
        internal static string APIChecker_ServerProtocolViolation {
            get {
                return ResourceManager.GetString("APIChecker_ServerProtocolViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เซิร์ฟเวอร์ไม่พร้อมใช้งาน.
        /// </summary>
        internal static string APIChecker_ServerUnavailable {
            get {
                return ResourceManager.GetString("APIChecker_ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL ล้มเหลว.
        /// </summary>
        internal static string APIChecker_SSLFailed {
            get {
                return ResourceManager.GetString("APIChecker_SSLFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเร็จ.
        /// </summary>
        internal static string APIChecker_Success {
            get {
                return ResourceManager.GetString("APIChecker_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมดเวลา.
        /// </summary>
        internal static string APIChecker_Timeout {
            get {
                return ResourceManager.GetString("APIChecker_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การตรวจสอบ Trust ล้มเหลว.
        /// </summary>
        internal static string APIChecker_TrustFailure {
            get {
                return ResourceManager.GetString("APIChecker_TrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อผิดพลาดที่ไม่รู้จัก.
        /// </summary>
        internal static string APIChecker_Unknown {
            get {
                return ResourceManager.GetString("APIChecker_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่รู้จัก Status Code ชุดนี้.
        /// </summary>
        internal static string APIChecker_UnknownStatusCode {
            get {
                return ResourceManager.GetString("APIChecker_UnknownStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัว Launcher ปิดเนื่องจากพบปัญหาของเธรด.
        /// </summary>
        internal static string Application_Exception_Thread {
            get {
                return ResourceManager.GetString("Application_Exception_Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัว Launcher ปิดเนื่องจากพบปัญหาที่ไม่สามารถจัดการได้.
        /// </summary>
        internal static string Application_Exception_Unhandled {
            get {
                return ResourceManager.GetString("Application_Exception_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกี่ยวกับ.
        /// </summary>
        internal static string Global_Text_About {
            get {
                return ResourceManager.GetString("Global_Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกการใช้งาน.
        /// </summary>
        internal static string Global_Text_EG_1 {
            get {
                return ResourceManager.GetString("Global_Text_EG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETA Build Date.
        /// </summary>
        internal static string KitEnabler_Beta {
            get {
                return ResourceManager.GetString("KitEnabler_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEV Build Date.
        /// </summary>
        internal static string KitEnabler_Dev {
            get {
                return ResourceManager.GetString("KitEnabler_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Date.
        /// </summary>
        internal static string KitEnabler_Public {
            get {
                return ResourceManager.GetString("KitEnabler_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้า Github ผ่านเว็ปเบราว์เซอร์ เพื่อดาวน์โหลด Game Launcher เวอร์ชั่นใหม่.
        /// </summary>
        internal static string LauncherUpdateCheck_FS {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_FS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ Launcher:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รุ่นทดสอบ.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Beta {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้พัฒนา.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Dev {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้าง.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Text_Build {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Text_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปัจจุบัน:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Text_Current {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Text_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เสถียร:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Text_Stable {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Text_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่เป็นทางการ.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Unofficial {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Unofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ Launcher:\n- API Version Error.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Invalid_Error {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Invalid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ Launcher:\n- Invalid JSON.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Invalid_JSON {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Invalid_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ Launcher:\n- เวอร์ชั่นล่าสุด.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_No_Update {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_No_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ Launcher:\n- Update Available.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Update {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล่าสุด:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Update_New {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Update_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวอร์ชั่น:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Version {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลืมรหัสผ่านไหม?.
        /// </summary>
        internal static string MainScreen_Button_Forgot_Password {
            get {
                return ResourceManager.GetString("MainScreen_Button_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        internal static string MainScreen_Button_Launch {
            get {
                return ResourceManager.GetString("MainScreen_Button_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        internal static string MainScreen_Button_Login {
            get {
                return ResourceManager.GetString("MainScreen_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เล่นทันที.
        /// </summary>
        internal static string MainScreen_Button_Play {
            get {
                return ResourceManager.GetString("MainScreen_Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียน.
        /// </summary>
        internal static string MainScreen_Button_Register {
            get {
                return ResourceManager.GetString("MainScreen_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเซิฟเวอร์.
        /// </summary>
        internal static string MainScreen_Button_SelectServer {
            get {
                return ResourceManager.GetString("MainScreen_Button_SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิด Launhcer.
        /// </summary>
        internal static string MainScreen_Context_Close {
            get {
                return ResourceManager.GetString("MainScreen_Context_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกมกำลังจะปิดตัวลงใน 5 นาที\nโปรดรีสตาร์ทด้วยตนเองก่อนที่ Launcher จะดำเนินการ.
        /// </summary>
        internal static string MainScreen_Notification_Text_Alert {
            get {
                return ResourceManager.GetString("MainScreen_Notification_Text_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บังคับรีสตาร์ท -.
        /// </summary>
        internal static string MainScreen_Notification_Text_Restart {
            get {
                return ResourceManager.GetString("MainScreen_Notification_Text_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เชิญเช้า Discord.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Discord {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่ม Facebook.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Facebook {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าเว็ปหลัก.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Home {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แพลตฟอม X.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Twitter {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main API\n- Pinging.
        /// </summary>
        internal static string MainScreen_Text_API_Launcher {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher ออฟไลน์.
        /// </summary>
        internal static string MainScreen_Text_API_Launcher_Description_Offline {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Launcher_Description_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เชื่อมต่อกับ API.
        /// </summary>
        internal static string MainScreen_Text_API_Launcher_Description_Online {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Launcher_Description_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้เล่นออนไลน์: ###\nผู้ลงทะเบียน: ###.
        /// </summary>
        internal static string MainScreen_Text_API_Server {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ Launcher:\n- สร้างโดย Linux.
        /// </summary>
        internal static string MainScreen_Text_FS_Launcher_Status_Linux {
            get {
                return ResourceManager.GetString("MainScreen_Text_FS_Launcher_Status_Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยินดีต้อนรับ.
        /// </summary>
        internal static string MainScreen_Text_FS_Login_Greeting {
            get {
                return ResourceManager.GetString("MainScreen_Text_FS_Login_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher\n- กำลังตรวจสอบ.
        /// </summary>
        internal static string MainScreen_Text_Launcher_Status {
            get {
                return ResourceManager.GetString("MainScreen_Text_Launcher_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวอร์ชั่น: v.
        /// </summary>
        internal static string MainScreen_Text_Launcher_Version {
            get {
                return ResourceManager.GetString("MainScreen_Text_Launcher_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ป้อนข้อมูลบัญชีของคุณเพื่อเข้าสู่ระบบ.
        /// </summary>
        internal static string MainScreen_Text_Login {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การซิ่งรถยามบ่ายก็น่าสนใจดีนะ.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_Afternoon {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วงนี้แหละ เหมาะกับการซิ่งเลยนะ.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_Evening {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เช้าๆแบบนี้ต้องออกไปซิ่งเพื่อยืดเส้นยืดสายสักหน่อยนะ.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_Morning {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ว่าไงเพื่อน ดึกๆแบบนี้จะไปไหนล่ะ.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_YouNeedSleep {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_YouNeedSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล Build Date: ##-##-##-X.
        /// </summary>
        internal static string MainScreen_Text_PH_InsiderBuildNumber {
            get {
                return ResourceManager.GetString("MainScreen_Text_PH_InsiderBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวอร์ชั่น: vX.X.X.X.
        /// </summary>
        internal static string MainScreen_Text_PH_Launcher_Version {
            get {
                return ResourceManager.GetString("MainScreen_Text_PH_Launcher_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: ธีมวันหยุด.
        /// </summary>
        internal static string MainScreen_Text_PH_SceneryGroup_Default {
            get {
                return ResourceManager.GetString("MainScreen_Text_PH_SceneryGroup_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดรอ....
        /// </summary>
        internal static string MainScreen_Text_PlayProgress {
            get {
                return ResourceManager.GetString("MainScreen_Text_PlayProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลถูกซ่อนไว้.
        /// </summary>
        internal static string MainScreen_Text_Protection_Email {
            get {
                return ResourceManager.GetString("MainScreen_Text_Protection_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: ธีมคริสมัส.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Christmas {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต่นี่มัน ฉันเอง!.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_EG_1 {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_EG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: ธีม Halloween.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Halloween {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Halloween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: ธีมปีใหม่.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_NewYears {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_NewYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: ธีมปกติ.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Normal {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: ธีม Oktoberfest.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Oktoberfest {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Oktoberfest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: ธีมวาเลนไทน์.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Valentines {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Valentines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิงไปที่เซิร์ฟเวอร์.
        /// </summary>
        internal static string MainScreen_Text_ServerPingStatus {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerPingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะเวลาที่เล่น:.
        /// </summary>
        internal static string MainScreen_Text_ServerShutDown {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Launcher!.
        /// </summary>
        internal static string MainScreen_Text_ServerShutDown_EG_1 {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerShutDown_EG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะเซิร์ฟเวอร์:\n - Pinging.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Checking {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล้มเหลวในการเชื่อมต่อกับเซิร์ฟเวอร์.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Cancelled {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูเหมือนว่าเซิร์ฟเวอร์จะออฟไลน์.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Offline {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออนไลน์: {0}\n ลงทะเบียน: {1}.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Online {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ได้รับข้อมูลจากเซิร์ฟเวอร์เกมที่ไม่ถูกต้อง.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Unstable {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะเซิร์ฟเวอร์:\n - ออฟไลน์.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Offline {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะเซิร์ฟเวอร์:\n - ออนไลน์.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Online {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher ออฟไลน์:\n - ไม่ทราบข้อมูล.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Unknown {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การเชื่อมต่อเซิร์ฟเวอร์:\n - ไม่เสถียร.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Unstable {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดรอในขณะที่ Launcher ยังคงดาวน์โหลดไฟล์เกมอยู่.
        /// </summary>
        internal static string MainScreen_TextBox_GameFiles_Downloading {
            get {
                return ResourceManager.GetString("MainScreen_TextBox_GameFiles_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบไดรฟ์ {0}\nไดเร็กทอรีการติดตั้งจริงของคุณถูกตั้งค่าเป็น {1} ในขณะนี้.
        /// </summary>
        internal static string MainScreen_TextBox_GameFiles_Invalid_Location {
            get {
                return ResourceManager.GetString("MainScreen_TextBox_GameFiles_Invalid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าจอการตั้งค่าพบข้อผิดพลาด.
        /// </summary>
        internal static string MainScreen_TextBox_SettingsScreen_Error {
            get {
                return ResourceManager.GetString("MainScreen_TextBox_SettingsScreen_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์ไม่ถูกต้อง.
        /// </summary>
        internal static string Program_TextBox_File_Invalid {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่รองรับ CPU ที่คุณใช้.
        /// </summary>
        internal static string Program_TextBox_File_Invalid_CPU {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเริ่ม Launcher ได้\nไฟล์ต่อไปนี้ไม่ถูกต้อง:\n\n.
        /// </summary>
        internal static string Program_TextBox_File_Invalid_Start {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวอร์ชันไม่ถูกต้อง.
        /// </summary>
        internal static string Program_TextBox_File_Invalid_Version {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบไฟล์.
        /// </summary>
        internal static string Program_TextBox_File_NotFound {
            get {
                return ResourceManager.GetString("Program_TextBox_File_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุญาตให้ใช้ Launcher ที่อยู่ใน Location นี้.
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุญาตให้ใช้ Location นี้:.
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ตำแหน่งของโฟลเดอร์ต้องอยู่ในไดรฟ์ เช่น C:\\ หรือ D:\\).
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Includes &apos;Desktop&apos;, &apos;Documents&apos;, &apos;Downloads&apos;).
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P4 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้ย้ายโฟลเดอร์ Launcher ไปที่อื่นแทน เช่น:.
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P5 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หรือ.
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P6 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (หรือตำแหน่งไดรฟ์ของ NTFS อื่น ๆ เช่น &apos;D:&apos;).
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P7 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำการทดสอบการเขียนไปยังโฟลเดอร์ที่มี Launcher ได้\nเนื่องจากไม่มีสิทธิ์การใช้งาน.
        /// </summary>
        internal static string Program_TextBox_Folder_Write_Test {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Write_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขณะนี้ Need for Speed: World กำลังทำงานอยู่.
        /// </summary>
        internal static string Program_TextBox_GameIsRunning {
            get {
                return ResourceManager.GetString("Program_TextBox_GameIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดไฟล์ LZMA.dll ที่หายไป\nกรุณารีสตาร์ท Launcher ขอบคุณ!.
        /// </summary>
        internal static string Program_TextBox_LZMA_Redownloaded {
            get {
                return ResourceManager.GetString("Program_TextBox_LZMA_Redownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แอปพลิเคชันนี้ต้องการเวอร์ชันขั้นต่ำของ .NET Framework:\n.
        /// </summary>
        internal static string Program_TextBox_NetFrame_P1 {
            get {
                return ResourceManager.GetString("Program_TextBox_NetFrame_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการติดตั้ง .NET Framework เวอร์ชันนี้ทันทีหรือไม่.
        /// </summary>
        internal static string Program_TextBox_NetFrame_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_NetFrame_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเริ่มแอปพลิเคชันนี้ได้.
        /// </summary>
        internal static string Program_TextBox_NetFrame_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_NetFrame_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขณะนี้ Launcher กำลังทำงานอยู่.
        /// </summary>
        internal static string Program_TextBox_SBRWIsRunning {
            get {
                return ResourceManager.GetString("Program_TextBox_SBRWIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขณะนี้ Simplified Launcher กำลังทำงานอยู่.
        /// </summary>
        internal static string Program_TextBox_SimplifiedIsRunning {
            get {
                return ResourceManager.GetString("Program_TextBox_SimplifiedIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System ตรวจพบว่าระบบตรวจสอบมีข้อผิดพลาด.
        /// </summary>
        internal static string Program_TextBox_System_Detection {
            get {
                return ResourceManager.GetString("Program_TextBox_System_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สวัสดีคุณผู้ใช้ Windows 7:\nเราตรวจพบปัญหาที่อาจเกิดขึ้นจากการอัปเดตที่ขาดหายไปซึ่งอาจจำเป็น.
        /// </summary>
        internal static string Program_TextBox_W7_KB_P1 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เราพบว่าแพ็คเกจ Windows Update เหล่านี้ไม่ได้ถูกติดตั้ง:.
        /// </summary>
        internal static string Program_TextBox_W7_KB_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Program_TextBox_W7_KB_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณสามารถกด &apos;OK&apos; เพื่อดำเนินการต่อ และคุณจะไม่เห็นข้อความนี้อีก.
        /// </summary>
        internal static string Program_TextBox_W7_KB_P4 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ: ไม่พบ Registry Key ต่อไปนี้:.
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P1 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องมีการตั้งค่านี้เพื่อให้ Launcher ทำงานได้อย่างถูกต้อง!.
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การคลิก &apos;OK&apos; จะพยายามเพิ่มการตั้งค่า Registry Key.
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การตั้งค่า Registry Key\n\nโปรดจำไว้ว่าการเปลี่ยนแปลงอาจต้องรีบูตระบบจึงจะมีผล.
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P4 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณจะต้องติดตั้ง 32-bit 2015-2019 VC++ Redistributable Package (หรือใหม่กว่า).
        /// </summary>
        internal static string Redistributable_VC_32 {
            get {
                return ResourceManager.GetString("Redistributable_VC_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณจะต้องติดตั้ง 64-bit 2015-2019 VC++ Redistributable Package (หรือใหม่กว่า).
        /// </summary>
        internal static string Redistributable_VC_64 {
            get {
                return ResourceManager.GetString("Redistributable_VC_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล้มเหลวในการติดตั้งแพ็คเกจเสริม\nตัวเกมจะไม่ทำงาน.
        /// </summary>
        internal static string Redistributable_VC_P10 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การติดตั้งนี้จะทำงานอยู่เบื้องหลัง.
        /// </summary>
        internal static string Redistributable_VC_P2 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาจจะต้องรีสตาร์คอมพิวเตอร์ของคุณ.
        /// </summary>
        internal static string Redistributable_VC_P3 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลิก OK เพื่อติดตั้ง.
        /// </summary>
        internal static string Redistributable_VC_P4 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        internal static string Redistributable_VC_P5 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล้มเหลวในการเรียกตัวติดตั้งแพ็คเกจเสริม\nตัวเกมจะไม่ทำงาน.
        /// </summary>
        internal static string Redistributable_VC_P6 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล้มเหลวในการเรียกตัวติดตั้งแพ็คเกจเสริม\n Exit Code ของตัวติดตั้ง.
        /// </summary>
        internal static string Redistributable_VC_P7 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเริ่มเกมได้.
        /// </summary>
        internal static string Redistributable_VC_P8 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล้มเหลวในการเปิดตัวติดตั้งแพ็คเกจเสริม\nตัวเกมจะไม่ทำงาน.
        /// </summary>
        internal static string Redistributable_VC_P9 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์ได้\nโปรดตรวจสอบการเชื่อมต่อของคุณ\n\nคลิก Yes เพื่อปิด Launcher\n\nหรือ\n\nคลิก No เพื่อดำเนินการต่อ.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher หยุดทำงานแล้ว ไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์ได้.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API_P2 {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดเก็บข้อมูลการทำงานที่ผิดพลาดของ Launcher นี้ไว้\nเพื่อที่จะได้นำไปใช้แก้ไขปัญหาในอนาคต.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API_P3 {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher จะยังคงดำเนินต่อไป แม้ว่าจะไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์ได้ก็ตาม.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API_P4 {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API_P4", resourceCulture);
            }
        }
    }
}
